- hosts: all
  user: vagrant
  become: true
  become_method: sudo

  tasks:
    - name: add fpcomplete key
      apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/debian/fpco.key state=present

    - name: add stack repo
      apt_repository: repo='deb http://download.fpcomplete.com/debian/jessie stable main' state=present

    - name: Installing packages
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
        - stack

    - name: Creating db
      become_user: postgres
      postgresql_db:
        name: cuti

    - name: Creating db user
      become_user: postgres
      postgresql_user:
        db: cuti
        name: kingcrimson
        password: NingenIsu
        role_attr_flags: SUPERUSER
