- hosts: all
  user: vagrant
  become: yes
  become_method: sudo

  tasks:
    - name: add fpcomplete key
      apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/debian/fpco.key state=present

    - name: add stack repo
      apt_repository: repo='deb http://download.fpcomplete.com/debian/jessie stable main' state=present

    - name: Installing packages
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - postgresql
        - stack
